/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package co.com.MASGlobalConsulting.microservice.employee.api;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import co.com.MASGlobalConsulting.microservice.employee.model.Errors;
import co.com.MASGlobalConsulting.microservice.employee.model.GetEmployeeRequest;
import co.com.MASGlobalConsulting.microservice.employee.model.GetEmployeeResponse;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-09-20T19:10:52.217-05:00")

@Api(value = "employeeInformation", description = "the employeeInformation API")
public interface EmployeeInformationApi {

    @ApiOperation(value = "obtain employees information", nickname = "employeeInformationPost", notes = "Obtains the information of the employees with their respective calculated annual salary", response = GetEmployeeResponse.class, tags={ "obtain-employee-information-api-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Information employees successfully returned", response = GetEmployeeResponse.class),
        @ApiResponse(code = 424, message = "Business exception", response = Errors.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = Errors.class) })
    @RequestMapping(value = "/employeeInformation",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    <T> ResponseEntity<T> employeeInformationPost(@ApiParam(value = "body" ,required=true )  @Valid @RequestBody GetEmployeeRequest body);

}
